### ISSUE TITLE
The program is not running. Missing files eg. src/main/FlightControllers/controlGains/oldCtrlGains.mat

### ISSUE THREAD

**Issue by ayan1991** [pheidlauf/AeroBenchVV#12]
The program is not running. Missing files eg. src/main/FlightControllers/controlGains/oldCtrlGains.mat

**Comment by stanleybak** [comment]
This is fixed in this pull request which Peter hasn't merged yet: https://github.com/pheidlauf/AeroBenchVV/pull/11

For now, you can clone the develop branch from my fork which has the gain matrices (in addition to other fixes): https://github.com/stanleybak/AeroBenchVV/tree/develop
